---
title: "Computational_Finance"
output: html_document
date: "October 20, 2016"
---
 - 181 stock market adjusted closing prices for Starbucks (SBUX)
 - assign .csv data to `data_url` using `read.csv()`
```{r, results='asis'}
data_url <- 'sbuxPrices.csv'
sbux_df <- read.csv(data_url, header=T, stringsAsFactors=F)
print(sbux_df)
```
 - check data frame
```{r}
print(str(sbux_df))  # structure
print(head(sbux_df))  # first lines
print(tail(sbux_df))  # last lines
class('Date')  # character
```
 - `drop=F` maintains vertical column
 - assign `Adj.Close` to `closing_prices`
```{r}
closing_prices <- sbux_df[, 'Adj.Close', drop=F]
print(closing_prices)
```
 - assign `Date` indices
```{r}
date_1 <- which(sbux_df$Date=='3/1/1994')
date_2 <- which(sbux_df$Date=='3/1/1995')
dated_prices <- sbux_df$Adj.Close[date_1 : date_2]
print(dated_prices)
```
 - assign `Adj.Close` to `sbux_prices_df`
```{r}
sbux_prices_df <- sbux_df[, 'Adj.Close', drop=FALSE]
```

 - assign dates as row names (indices)
```{r}
rownames(sbux_prices_df) <- sbux_df$Date
head(sbux_prices_df)
```
 - assign date indices
```{r}
price_1 <- sbux_prices_df["3/1/1994", 1]
price_2 <- sbux_prices_df["3/1/1995", 1]
print(price_1)
print(price_2)
```
 - plot `Adj.Close`
```{r}
plot(sbux_df$Adj.Close, type = "l", col="blue", lwd=2, 
     ylab="Adjusted Close", 
     main="Monthly Closing Price of Starbucks (SBUX)")
     legend(x='topleft', legend='Starbucks (SBUX)', 
     lty=1, lwd=2, col='blue')
```
